  - name: LÖVE Build
  # You may pin to the exact commit or the version.
  # uses: nhartland/love-build@59f670bb62a027a04e6d0cc3502f807b5365ef8e
  uses: nhartland/love-build@v1
  with:
    # Name of the application to be built
    app_name: FNFFD LOVE2D
    # Version of LÖVE to be used in building the application
    love_version: # default is 11.5
    # Path to dependencies rockspec relative to GitHub workspace
    dependencies: # optional
    # Path in the repository to the subdirectory containing `main.lua`. By default the repo root
    source_dir: # default is ./
    # Directory in the GitHub workspace where the built distributables should be located
    result_dir: # default is release
          
