name: Build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]
jobs:
  build-game:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        love_version: ['11.5']
    steps:
    - uses: actions/checkout@v4
    - uses: nhartland/love-build@v1
      id: love-build
      with:
        app_name: 'fnffd_love2d'
        love_version: ${{ matrix.love_version }}
        source_dir: './'
    # Upload the resulting artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: hw_win32-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v4
      with:
        name: hw_win64-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v4
      with:
        name: hw_love-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.love-filename }}
    - uses: actions/upload-artifact@v4
      with:
        name: hw_linux_x86_64-build-${{ matrix.love_version}}
        path: ${{ steps.love-build.outputs.linux_x86_64-filename }}
