name: continuous-integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
        submodules: true
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install --assume-yes wine-stable wine64 python3-pip
    - name: Install makelove
      run: pip3 install makelove
    - name: Build
      run: cd main/ && python3 -m makelove

# SHUT UP AND LET ME HARDCODE IT
    - name: Artifact (love)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME_LOVE }}
        path: main/makelove-build/love/fnffd
    - name: Artifact (AppImage)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME_APPIMAGE }}
        path: main/makelove-build/appimage/fnffd
    - name: Artifact (Win64)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME_WIN64 }}
        path: main/makelove-build/win64/fnffd
